hotels:
  - slug: "metropol-moscow"
    name: "Метрополь Москва"
    city: "Москва"
    stars: 5
    website: "https://metropol-moscow.ru"
    sources:
      ostrovok:
        url_template: "https://ostrovok.ru/hotel/russia/moscow/mid7595994/metropol_hotel/?dates={checkin_dot}-{checkout_dot}&guests={adults}&search=yes"
      ozon_travel:
        url_template: "https://www.ozon.ru/travel/hotels/product/613318873/?Dlts={adults}&checkIn={checkin}&checkOut={checkout}"
      hotel_site:
        url_template: "https://ru-ibe.tlintegration.ru/booking2/hotel/index.gc.html?providerId=6315&arrivalDate={checkin}&departureDate={checkout}&adults={adults}&language=ru"
        has_dates: true
        widget: travelline
      otello:
        url_template: "https://otello.ru/hotel/4504127908386113?checkin={checkin}&checkout={checkout}&guest_groups=%5B%7B%22adults%22%3A{adults}%7D%5D"

  - slug: "radisson-collection-moscow"
    name: "Radisson Collection Москва"
    city: "Москва"
    stars: 5
    sources:
      ostrovok:
        url_template: "https://ostrovok.ru/hotel/russia/moscow/mid8876782/radisson_collection_hotel_moscow/?dates={checkin_dot}-{checkout_dot}&guests={adults}&search=yes"
      ozon_travel:
        url_template: "https://www.ozon.ru/travel/hotels/product/612656495/?Dlts={adults}&checkIn={checkin}&checkOut={checkout}"
      hotel_site:
        url_template: "https://ru-ibe.tlintegration.ru/booking2/hotel/index.gc.html?providerId=17489&arrivalDate={checkin}&departureDate={checkout}&adults={adults}&language=ru"
        has_dates: true
        widget: travelline
      otello:
        url_template: "https://otello.ru/hotel/4504127908393745?checkin={checkin}&checkout={checkout}&guest_groups=%5B%7B%22adults%22%3A{adults}%7D%5D"


schedule:
  checkin_offsets_days: [3]
  adults: 2
